### ISSUE TITLE
RuntimeError: The size of tensor a (938) must match the size of tensor b (470) at non-singleton dimension 3

### ISSUE THREAD

**Issue by lvxiaoqian** [xl-tang3/UAUDeblur#2]
when running the UaUDeblur_demo.py, I meet an error as follows:
line 150, in closure
    self.img_blurred_torch)  + self.Lambda1* self.sploss(dct_2d(self.s))  + self.Lambda2* self.sploss(self.w)+0.05*self.tv(self.img_out_torch)
RuntimeError: The size of tensor a (938) must match the size of tensor b (470) at non-singleton dimension 3

 How to solve this problem？

**Comment by lvxiaoqian** [comment]
and what the version of the pytorch？

**Comment by xl-tang3** [comment]
It's PyTorch 1.10.1 and personally this error does not occur in my environment.
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/14/2023 11:05 |
| To | xl-tang01/UAUDeblur ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | Re: [xl-tang01/UAUDeblur] TypeError: can't convert np.ndarray of type numpy.complex128. (Issue #2) |

and what the version of the pytorch？

**Comment by lvxiaoqian** [comment]
Thanks! I've solved the problem. How to show experimental results for color images？
