### ISSUE TITLE
How to show experimental results for color images？

### ISSUE THREAD

**Issue by lvxiaoqian** [xl-tang3/UAUDeblur#3]

**Comment by xl-tang3** [comment]
1. I'd like to recommend to change the number of outout channel (the second parameter) from 1 into 3. 


2. It's also appreciated if you do it channel by channel and stack three network estimates  into RGB format.
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/22/2023 16:26 |
| To | xl-tang01/UAUDeblur ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [xl-tang01/UAUDeblur] How to show experimental results for color images？ (Issue #3) |

**Comment by lvxiaoqian** [comment]
> 1. I'd like to recommend to change the number of outout channel (the second parameter) from 1 into 3. 2. It's also appreciated if you do it channel by channel and stack three network estimates into RGB format. ---- Replied Message ---- | From | ***@***.***> | | Date | 07/22/2023 16:26 | | To | xl-tang01/UAUDeblur ***@***.***> | | Cc | Subscribed ***@***.***> | | Subject | [xl-tang01/UAUDeblur] How to show experimental results for color images？ (Issue #3) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Is "img_out.mat" the final result? How to visualize it in "png"？
