### ISSUE TITLE
where to download the dataset for Levin et al. [13] and Lai et al. [12]?

### ISSUE THREAD

**Issue by wwxb2012** [xl-tang3/UAUDeblur#7]
I searched for them but found that the claimed dataset link for both of them failed. Could you share the dataset? 百度云也行.

original links:
Levin et al. [13]: http://vllab.ucmerced.edu/wlai24/cvpr16_deblur_study/
Lai et al. [12]: www.wisdom.weizmann.ac.il/˜levina/papers/LevinEtalCVPR09Data.zip

**Comment by xl-tang3** [comment]
你好，可以在这里下载到

https://drive.google.com/drive/folders/1WlAb4hC2KzDNfl_GkFimw2x66USZpKwe



At 2023-12-11 12:33:16, "wwxb2012" ***@***.***> wrote:

I searched for them but found that the claimed dataset link for both of them failed. Could you share the dataset? 百度云也行.

original links:
Levin et al. [13]: http://vllab.ucmerced.edu/wlai24/cvpr16_deblur_study/
Lai et al. [12]: www.wisdom.weizmann.ac.il/˜levina/papers/LevinEtalCVPR09Data.zip
